listen_on_interface: "eth0"
nftables_table_name: "go-knop-tbl"
nftables_chain_name: "go-knop-chain"
max_packet_length: 65535

users:
  - name: "alice"
    aes_key: "VqXkBl8jJ/FG9wh0jSlWcgRhxxYo+1IxzD/HHvzRtSs="

rules:
  - name: "ssh-access"
    knock_port: 62201
    open_proto: "tcp"
    open_port: 22
    open_time: 15
    allowed_users:
      - "alice"